spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:file:./data/notificationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1
    listener:
      ack-mode: record
      concurrency: 1
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8084

logging:
  pattern:
    level: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] %5p %c - %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

notification-service:
  notification:
    notification-type: fake
  sendgrid:
    api-key: ${SENDGRID_API_KEY:CREATE_ENV_VARIABLES}
    from-email: ${SENDGRID_FROM_EMAIL:CREATE_ENV_VARIABLES}
    from-name: ${SENDGRID_FROM_NAME:CREATE_ENV_VARIABLES}
