spring:
  application:
    name: client-service
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  datasource:
    url: jdbc:postgresql://localhost:5434/clientdb
    driver-class-name: org.postgresql.Driver
    username: client_service
    password: client_service
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

app:
  security:
    issuer-uri: http://localhost:8180/realms/payment-microservice
    jwk-set-uri: http://localhost:8180/realms/payment-microservice/protocol/openid-connect/certs

logging:
  pattern:
    level: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] %5p %c - %m%n"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

client-service:
  outbox:
    retry-delay-ms: 43200000
  keycloak:
    token-uri: http://localhost:8180/realms/payment-microservice/protocol/openid-connect/token
    admin-base-uri: http://localhost:8180/admin/realms/payment-microservice
    client-id: client-service
    client-secret: client-service-secret
    default-password: client123
    client-role-name: CLIENT

resilience4j:
  retry:
    instances:
      defaultProducerRetry:
        max-attempts: 3
        wait-duration: 1000ms
        retry-exceptions:
          - java.io.IOException
          - com.fasterxml.jackson.core.JsonProcessingException
          - org.springframework.dao.DataAccessException
