apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-registry/
  - client-service/
  - order-service/
  - payment-service/
  - notification-service/
  - api-gateway/
