spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
grpc:
  server:
    port: 9090
server:
  port: 8083

eureka:
  instance:
    metadata-map:
      grpc-port: 9090
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  retry:
    instances:
      defaultProducerRetry:
        max-attempts: 3
        wait-duration: 1000ms
        retry-exceptions:
          - java.io.IOException
          - com.fasterxml.jackson.core.JsonProcessingException
          - org.springframework.dao.DataAccessException
