# src/main/resources/application.yml

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:file:./data/orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.clientservice.model.*, br.com.orderservice.model.*, br.com.clientservice.events.*, br.com.orderservice.events.*"
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 500
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/