name: CI - Build and Test all services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build all services
        run: ./gradlew clean build -x :e2e-tests:test --no-daemon

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          services=("api-gateway" "client-service" "notification-service" "order-service" "payment-service" "service-registry")

          for service in "${services[@]}"; do
            image="jorgeeduardo96/payment-microservice-${service}:latest"
            docker build \
              --build-arg GITHUB_USERNAME=$GITHUB_USERNAME \
              --build-arg GITHUB_TOKEN=$GITHUB_TOKEN \
              -t $image ./$service
          done

      - name: Run E2E tests
        run: ./gradlew :e2e-tests:test --no-daemon

      - name: Push Docker images
        run: |
          services=("api-gateway" "client-service" "notification-service" "order-service" "payment-service" "service-registry")

          for service in "${services[@]}"; do
            docker push "jorgeeduardo96/payment-microservice-${service}:latest"
          done
